### ISSUE TITLE
allow news editing to non-admin users

### ISSUE THREAD

**Issue by gustavo-roganti-extera** [dachcom-digital/pimcore-news#19]
How can we allow a backend user to edit news without being an admin?

It seems that only the admin is able to edit any news. All the others receive this message:
`You have no permission to open this news object type. Entry Type is:`

It seems that some of this behaviour si due to this code:
`if(!$user->isAdmin()) {
                $data['_invalidEntryType'] = TRUE;`
in /NewsBundle/EventListener/EntryTypeListener.php

but fixing that is not enough: the news edit page loads but the news type select box remains empty.

Does anybody know how to proceed?

**Comment by dennistiboni-extera** [comment]
Hi @solverat have an answer for this question?
the end customer could use this plugin, but normally he his the Editor or a limited user.

regards

**Comment by solverat** [comment]
It seems that you don't have any entry types configured. 
you always need a default entry type, for example:

```yml
news:
    entry_types:
        default: 'news' # the default entry type to start with
            items:
                news:
                    name: 'news.entry_type.news'
                    route: 'news_detail'
                    custom_layout_id: 0
```
read more about the entry types here: https://github.com/dachcom-digital/pimcore-news/blob/master/docs/20_EntryTypes.md
